### PR TITLE
add basic course hugo config

### PR DESCRIPTION
**Pull request by gumaerc**
This PR adds the basic Hugo config for course sites built using the `course` theme as well as an empty `ocw-studio` config

To test this PR:
 - Clone https://github.com/mitodl/ocw-hugo-themes
 - From `ocw-hugo-themes` directory, run `yarn install && npm run start:site:webpack`
 - Clone https://github.com/mitodl/ocw-to-hugo
 - Create markdown for any course using the instructions in the readme
 - From any course in your output directory, run:
 ```
hugo server --config /path/to/ocw-hugo-projects/ocw-course/config.yaml --themesDir /path/to/ocw-hugo-themes/
 ```

The course site should be spun up at http://localhost:1313

### CODE REVIEW

**Comment by mbertrand** [comment]
Getting this error on the last step:
```
Error: Error building site: "/Users/mattbert/code/ocw-to-hugo/output/18-03sc-differential-equations-fall-2011/content/_index.md:13:54": failed to extract shortcode: template for shortcode "baseurl" not found
```

**Comment by mbertrand** [comment]
Ok, command should be `hugo server --config /path/to/ocw-hugo-projects/ocw-course/config.yaml` but now I get another error:

```
Error: Error building site: failed to render pages: render of "home" failed: "/Users/mattbert/code/ocw-hugo-themes/course/layouts/course/course_home.html:45:14": 
execute of template failed: template: course/course_home.html:45:14: 
executing "main" at <len $courseData.other_versions>: error calling len: reflect: call of reflect.Value.Type on zero Value
```

**Comment by gumaerc** [comment]
@mbertrand Sorry, I renamed the `course` project to `ocw-course` to avoid collisions with the existing starter in `ocw-studio` and forgot to update the instructions.  However, I just tried this with `18-03sc-differential-equations-fall-2011` running:

`gumaerc@gumaerc-laptop:~/Code/ocw-to-hugo/private/output/18-03sc-differential-equations-fall-2011$ hugo server --config ~/Code/ocw-hugo-projects/ocw-course/config.yaml --themesDir ~/Code/ocw-hugo-themes`

I'm on the `main` branch of `ocw-hugo-themes` and the `master` branch of `ocw-to-hugo`.  The error you're seeing indicates that Hugo isn't able to find the course data template (`course.json`) and usually means that you're not running it with the right context.  Are you sure you're running it from the course's output directory?  You can also manually point at it with the `-s` argument if you'd like.  Can you give this another try with that in mind and let me know how it works out?

image

**Review by mbertrand — APPROVED** [review]
👍

**Pull request merged**
