### PR TITLE
added relevent highlights_text and related_content fields

### LINKED ISSUE #141: Support creation and editing of `"highlights_text"` and `"related_content"` in Studio
In https://github.com/mitodl/ocw-data-parser/issues/163 we persisted the legacy data for `highlights_text` and `related_content` into studio. 

In order for these fields to be exported to github from studio, they need to be added to the project file. 

These course metadata fields should be editable, and they should be exported to github so they can be published.

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #141 

#### What's this PR do?
Add related_content and hightlights_text option

#### How should this be manually tested?
Verify
- related_content
- hightlights_text
option appear in meta data for a course

### CODE REVIEW

**Comment by Wassaf-Shahzad** [comment]
A related PR https://github.com/mitodl/ocw-to-hugo/pull/491

**Review by mbertrand — COMMENTED** [review]
Looks good, needs a rebase though.

**Comment by pdpinch** [comment]
nit: can you change the PR title and the commit message to mention which fields you are adding? (add fields are relevant. if they weren't they wouldn't be in the project)

**Comment by Wassaf-Shahzad** [comment]
> nit: can you change the PR title and the commit message to mention which fields you are adding? (add fields are relevant. if they weren't they wouldn't be in the project)

Done

**Review by mbertrand — APPROVED** [review]
👍

**Comment by pdpinch** [comment]
@mbertrand @gumaerc is there any point in merging this? Would we ever be able to run this code?

**Comment by pdpinch** [comment]
@gumaerc is there any point in merging this? Would we ever be able to import the legacy data to populate these fields?

**Comment by gumaerc** [comment]
@pdpinch Since these are course level metadata properties, we couldn't use `overwrite_ocw_course_content` as-is. Currently it iterates the content in a course from `ocw-to-hugo` with:

```
    for resp in bucket.meta.client.get_paginator("list_objects").paginate(
        Bucket=bucket.name, Prefix=f"{site_prefix}/content"
    ):
```

As you can see, it's only iterating the `content` folder which contains the markdown for the course, and will only pull in fields from the metadata of content, not the course level metadata which is at `data/course_legacy.json` in this case. We maintain the course level metadata as a `WebsiteContent` object tied to the site with the type `sitemetadata`. So, we could pull in the data but would likely need to write a separate management command to do so, or modify the existing one to take arguments about where / what content to look at.

**Comment by pdpinch** [comment]
Ok. No one has asked about this in the past year. I'm going to close the PR and the issue. We can revisit if it surfaces again.

**Pull request closed without merging**
