### PR TITLE
added default value for resource

### LINKED ISSUE #173: ocw-course: default value for Draft should be false
As a user, it's annoying that I have to explicitly set "Draft" to false for new resources. I don't have to do this for other items, like pages. 

#### Acceptance Criteria:

- [ ] default value for "Draft" should be false

### PR DESCRIPTION
**Pull request by Wassaf-Shahzad**
#### Pre-Flight checklist

- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #173 

#### What's this PR do?
- adds 'False' as default value for resources draft field

#### How should this be manually tested?
- Verify resources created with this config have an initial value for false for draft

### CODE REVIEW

**Comment by MAbdurrehman12** [comment]
On adding a new resource on my local setup, the draft is already set to `false` so maybe the issue is about the new resources after syncing google drive. I haven't integrated the google drive locally so I'll integrate it and then test it.
In the meanwhile, if anyone else has already integrated drive and can test this PR, please feel free to un-assign me and review this PR.

**Review by MAbdurrehman12 — CHANGES_REQUESTED** [review]
For adding new resources, we have 2 options:

1. Add a resource manually (assuming that GDrive is not configured). In this case, `draft` value is already set to `false`, even if I don't use the config of this branch/PR.

2. Configure GDrive, upload a resource in drive and sync it with the site. In this case, resources don't have any value for `draft`, neither `true` nor `false`. If I repeat these step with the config of this branch/PR, in which we have set `default: false`, the behaviour is same. No value for draft, so I have to set it to true manually. 
image

Looks like this is a bug in `ocw-studio`

**Comment by pdpinch** [comment]
@ChristopherChudzicki were you fixing this, in https://github.com/mitodl/ocw-studio/pull/1363 ?

**Comment by ChristopherChudzicki** [comment]
@pdpinch @Wassaf-Shahzad PR https://github.com/mitodl/ocw-studio/pull/1363 should help with this... That PR makes it so that creating resources via g-drive sync will populate default values. So with https://github.com/mitodl/ocw-studio/pull/1363 **and** this PR both, resource "draft" would be populated via g-drive sync.

_If https://github.com/mitodl/ocw-studio/pull/1363 is merged, "license" will also be populated by g-drive sync, since it's default is already set._

**PS:** It might be good to set explicit defaults for "Draft" for all content types. Currently no content types has default values for "Draft", it's just a quirk of Studio's frontend that empty string is being coerced to `false` in the form.  (Or maybe the default should be `draft:true` to make publishing a more "active" choice? Whatever you think is best.)

**Comment by MAbdurrehman12** [comment]
> PR https://github.com/mitodl/ocw-studio/pull/1363 should help with this... That PR makes it so that creating resources via g-drive sync will populate default values. So with https://github.com/mitodl/ocw-studio/pull/1363 and this PR both, resource "draft" would be populated via g-drive sync.

Just tested this, and it works fine (default values in config are populated/reflected in studio upon creating resources via GDrive).

> It might be good to set explicit defaults for "Draft" for all content types

I agree.

**Review by MAbdurrehman12 — APPROVED** [review]
👍 

Do we also need to set `default: false` for `ocw-www` content? (pages, resource-collections, course-lists etc etc)

**Pull request merged**
